env:
    token: "ENCRYPTED[eb66dfc00c110d68a9adffccb35ba13a1e5bbd98e50bab0a10ca4592247ad043ac6b24934c406ab839a2b8eb67cf5bd6]"
    chat_id: "ENCRYPTED[51cf3402c739da39df00c038c950e96f7837acf9e66c1daa3e9eea842e1a352cacb002831dc7f585956ca8a2a8169e8e]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - git clone --depth=1 -b lime-q-oss https://github.com/c3eru/Xiaomi_Kernel_OpenSource_Bengal lv && cd lv
  
  Build_script:
      - ./build.sh
